name: CI

on:
  push:
    branches: [ main ]

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: rsync deployments
      run: |
        mkdir ~/.ssh
        echo "$remote_key" > ~/.ssh/gh_actions_key
        chmod 600 ~/.ssh/gh_actions_key
        rsync -avz --exclude '.git' --exclude '.well-known' -e "ssh -i ~/.ssh/gh_actions_key -o StrictHostKeyChecking=no" public/ $remote_user@$remote_host:$remote_path
      env:
        remote_path: ${{ secrets.REMOTE_PATH }}
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
  